// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdjvxocanfkhrmrvcfsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkanZ4b2NhbmZraHJtcnZjZnN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NDc2MjQsImV4cCI6MjA2NzUyMzYyNH0.QbgBYUVwLkt0L91SXRdsCw4S-TdCeP_FA3LAabT8n10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});